# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='post',
            new_name='plot',
        ),
    ]
